### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted 8(

### ISSUE THREAD

**Issue by LuwkasLima** [wpbrasil/wpbr-participe#6]
Jeeezzz

Alguem sabe o que se passa?

![image](https://cloud.githubusercontent.com/assets/5949986/5794389/866e2dc8-9f30-11e4-9b10-383c7437d3f3.png)

**Comment by duquebilly** [comment]
Gente, esse eh um dos arquivos com codigo malicioso q eu apontei no meu
ultimo email....

2015-01-18 20:40 GMT-02:00 Lucas Lima <notifications@github.com>:

**Comment by vmassuchetto** [comment]
O site parece ok. Esse erro tem dado aqui pra mim em outras páginas também,
especialmente quando a consulta é mais pesada.

Em 18 de janeiro de 2015 21:04, duquebilly <notifications@github.com>
escreveu:

**Comment by eduardozulian** [comment]
Vi o mesmo erro hoje ao acessar o http://traduza.wp-brasil.org
